spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bnade?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
# 日志设置格式 logging.level.* = LEVEL, *为包名或Logger名
logging:
  level:
    com:
      bnade: DEBUG